language: objective-c

osx_image: xcode8
xcode_sdk: iphonesimulator10.0

script:
- xcodebuild clean build test -project DKCameraDemo.xcodeproj -scheme DKCameraDemo -destination "platform=iOS Simulator,name=iPhone 6s"
