osx_image: xcode6.4

language: objective-c

#before_install:
#- export LANG=en_US.UTF-8
#- brew update
#- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

script:
- xcodebuild clean build test -project DKCameraDemo.xcodeproj -scheme DKCameraDemo -sdk iphonesimulator7.1
